# Project
version=1.0.0
group=sircow.noworldbordertint
java_version=25

# Common
minecraft_version=26.1
mod_name=No Worldborder Tint
mod_author=Sir_Cow
mod_id=noworldbordertint
license=MIT
credits=
description=Removes the world border vignette tint
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.1+26.1
fabric_loader_version=0.18.5
fabric_kotlin_version=1.13.9+kotlin.2.3.10
modmenu_version=18.0.0-alpha.6

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
